### ISSUE TITLE
Some usage examples would be helpful :)

### ISSUE THREAD

**Issue by mosheavni** [idanarye/nvim-buffls#1]
What is this plugin for?
how do you use it?
common cases?
examples?
Thanks!

**Comment by idanarye** [comment]
It'll probably make more sense to demonstrate it as part of a bigger [Moonicipal](https://github.com/idanarye/nvim-moonicipal) demonstration blog post. I'll add a link to the relevant section to  the readme once I write it.

**Comment by idanarye** [comment]
https://dev.to/idanarye/moonicipal-explained-4h02#data-cells-and-buffls
